# Generated by Django 3.1.1 on 2020-10-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=50)),
                ('measurements', models.FloatField()),
                ('measurements_type', models.CharField(max_length=6)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_class')),
            ],
        ),
        migrations.CreateModel(
            name='office_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_class')),
            ],
        ),
    ]
