# Generated by Django 3.1.2 on 2020-10-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cost',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_id', to='myapp.user_class'),
        ),
    ]
